linux_docker_builder:    
  timeout_in: 120m
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
    CIRRUS_CLONE_DEPTH: 0
  script: |
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG}-amd64 . -f Dockerfile
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}-amd64

linuxarmv7_docker_builder:    
  timeout_in: 120m
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
    CIRRUS_CLONE_DEPTH: 0
  script: |
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG}-armv7 . -f Dockerfile.rpi --build-arg ARCH=armv7l --build-arg CROSSCOMPILER=https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspberry%20Pi%20GCC%20Cross-Compiler%20Toolchains/GCC%209.1.0/Raspberry%20Pi%202%2C%203/cross-gcc-9.1.0-pi_2-3.tar.gz --build-arg IMAGE=balenalib/raspberry-pi2
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}-armv7

linuxarmv6_docker_builder:    
  timeout_in: 120m
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
    CIRRUS_CLONE_DEPTH: 0
  script: |
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker build -t $CIRRUS_REPO_FULL_NAME:${TAG}-armv6 . -f Dockerfile.rpi 
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker push $CIRRUS_REPO_FULL_NAME:${TAG}-armv6

windows_docker_builder:    
  only_if: $CIRRUS_TAG == ''
  timeout_in: 120m
  platform: windows
  os_version: 2019  
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
    CIRRUS_CLONE_DEPTH: 0
  script: |
    docker info
    set TAG=latest
    docker build --no-cache -t %CIRRUS_REPO_FULL_NAME%:%TAG%-windows . -f Dockerfile.windows
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS% 
    docker push %CIRRUS_REPO_FULL_NAME%:%TAG%-windows   

windowstag_docker_builder:
  only_if: $CIRRUS_TAG != ''
  timeout_in: 120m
  platform: windows
  os_version: 2019
  env:
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
    CIRRUS_CLONE_DEPTH: 0
  script: |
    docker info
    set TAG=%CIRRUS_TAG%
    docker build --no-cache -t %CIRRUS_REPO_FULL_NAME%:%TAG%-windows . -f Dockerfile.windows
    docker login --username=%DOCKERHUB_USER% --password=%DOCKERHUB_PASS%
    docker push %CIRRUS_REPO_FULL_NAME%:%TAG%-windows

    
publish_docker_builder:
  depends_on: 
    - linuxarmv6
    - linuxarmv7
    - linux
    - windows
    - windowstag
  env:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKERHUB_USER: ENCRYPTED[ccd1af2835558f6b3e08fa3dd8ad95e7b3eaf3b83220433093d6335a3f4727f4c53c4053587d1594799e72e331d1017d]
    DOCKERHUB_PASS: ENCRYPTED[7b81d2ca7878761ea497619cae892e267c0e0fdee71d8ce48dcd4ba11b9351a9d3f2f781dce84a7f8aab92a278007509]
  script: | 
    docker info
    export TAG=${CIRRUS_TAG:-latest}
    docker login --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASS 
    docker manifest create --amend $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-amd64 $CIRRUS_REPO_FULL_NAME:${TAG}-armv6 $CIRRUS_REPO_FULL_NAME:${TAG}-armv7 $CIRRUS_REPO_FULL_NAME:${TAG}-windows
    docker manifest annotate $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-armv7 --os linux --arch arm --variant v7
    docker manifest annotate $CIRRUS_REPO_FULL_NAME:${TAG} $CIRRUS_REPO_FULL_NAME:${TAG}-armv6 --os linux --arch arm --variant v6
    docker manifest push $CIRRUS_REPO_FULL_NAME:${TAG} -p
