image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_x86_64:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

build_rpi:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:rpi . -f Dockerfile.rpi
    - docker push $CI_REGISTRY_IMAGE:rpi

